services:
  bot:
    build:
      dockerfile: ./Dockerfile
    container_name: larpbot
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      TOKEN: "${TOKEN}"
      APP_ID: "${APP_ID}"
      TARGET_GUILD_ID: "${TARGET_GUILD_ID}"
      TARGET_CHANNEL_ID: "${TARGET_CHANNEL_ID}"
      MEMBER_ROLE_ID: "${MEMBER_ROLE_ID}"
      ACTION_THRESHOLD: "${ACTION_THRESHOLD:-3}"
      REDIS_URL: "${REDIS_URL}"

  redis:
    image: redis:8.2.1
    container_name: larpbot-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
